# Generated by Django 3.2 on 2021-05-03 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_movie_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='averagerating',
            field=models.FloatField(default=0),
        ),
    ]
